name: Build
on:
  push:
    branches:
      - transifex

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openstandia/keycloak-documentation-i18n:asciidoctor
      options: -v ${{ github.workspace }}:/build
    steps:
      - uses: actions/checkout@v2
      - name: Build documents
        run: /build/build.sh

